/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Operation.OperationManager;
import Person.AppManager;
import Person.Person;
import Person.PersonManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dazzl
 */
public class UserDashboard extends javax.swing.JFrame {

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        try {
            initComponents();
            AppManager.init();
            
            adminManageButton.setVisible(false);
            
            Person currentUser = AppManager.pm.getCurrentUser();
            headerLabel.setText("-------------------------------------- Welcome " + currentUser.getUsername() + "---------------------------------");
            
            if(currentUser.getUsername().equals("MarauderSquadron")){
                adminManageButton.setVisible(true);
            }
            
            OperationManager manager = new OperationManager();
            manager.populateOperationsButtons(JButton1, JButton2, JButton3, JButton4, JButton5, JButton6);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UserDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        OperationsPanel = new javax.swing.JPanel();
        JButton3 = new javax.swing.JButton();
        JButton4 = new javax.swing.JButton();
        JButton5 = new javax.swing.JButton();
        JButton6 = new javax.swing.JButton();
        JButton2 = new javax.swing.JButton();
        JButton1 = new javax.swing.JButton();
        PaymentsPanel = new javax.swing.JPanel();
        orgAccountPaymentButton = new javax.swing.JButton();
        TradeGoodsSoldButton = new javax.swing.JButton();
        SubdryAccountButton = new javax.swing.JButton();
        ORGdonationButton = new javax.swing.JButton();
        PaymentToAccountantButton = new javax.swing.JButton();
        adminManageButton = new javax.swing.JButton();
        PaymentCalculatorPanel = new javax.swing.JPanel();
        PaymentCalculatorHeaderLabel = new javax.swing.JLabel();
        TotalInLabel = new javax.swing.JLabel();
        NumberOfUsersLabel = new javax.swing.JLabel();
        MarauderSquadronLabel = new javax.swing.JLabel();
        DividerLabel = new javax.swing.JLabel();
        TotalProfitsLabel = new javax.swing.JLabel();
        TotalProfitsOutTextField = new javax.swing.JTextField();
        PaymentPerUserLabel = new javax.swing.JLabel();
        PaymentPerUserOutTextField = new javax.swing.JTextField();
        PaymentToMarauderSquadron = new javax.swing.JLabel();
        PaymentToMarauderOut = new javax.swing.JTextField();
        CalculateButton = new javax.swing.JButton();
        TotalInTextField = new javax.swing.JTextField();
        NumberOfUsersIntextField = new javax.swing.JTextField();
        MarauderSquadInTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerLabel.setText("---------------------------------------------------- WELCOME ----------------------------------------------------------------");

        OperationsPanel.setBackground(new java.awt.Color(255, 255, 255));

        JButton3.setText("Simple salvage");
        JButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton3ActionPerformed(evt);
            }
        });

        JButton4.setText("My oh my!?!");
        JButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton4ActionPerformed(evt);
            }
        });

        JButton5.setText("Hunting Holidays");
        JButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton5ActionPerformed(evt);
            }
        });

        JButton6.setText("Great Gatsby's house?");
        JButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton6ActionPerformed(evt);
            }
        });

        JButton2.setText("Breaker yard blockade");
        JButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton2ActionPerformed(evt);
            }
        });

        JButton1.setText("Chrome spoon");
        JButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OperationsPanelLayout = new javax.swing.GroupLayout(OperationsPanel);
        OperationsPanel.setLayout(OperationsPanelLayout);
        OperationsPanelLayout.setHorizontalGroup(
            OperationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperationsPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(OperationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(JButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        OperationsPanelLayout.setVerticalGroup(
            OperationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperationsPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(JButton1)
                .addGap(18, 18, 18)
                .addComponent(JButton2)
                .addGap(30, 30, 30)
                .addComponent(JButton3)
                .addGap(35, 35, 35)
                .addComponent(JButton4)
                .addGap(36, 36, 36)
                .addComponent(JButton5)
                .addGap(43, 43, 43)
                .addComponent(JButton6)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        PaymentsPanel.setBackground(new java.awt.Color(255, 255, 255));

        orgAccountPaymentButton.setText("Payment to Org Account");
        orgAccountPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgAccountPaymentButtonActionPerformed(evt);
            }
        });

        TradeGoodsSoldButton.setText("Log Trade goods sold");

        SubdryAccountButton.setText("Sundry Payments");

        ORGdonationButton.setText("ORG ACCOUNT DONATION");

        PaymentToAccountantButton.setText("Payment to Accountant");

        adminManageButton.setText("Manage Users");
        adminManageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminManageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaymentsPanelLayout = new javax.swing.GroupLayout(PaymentsPanel);
        PaymentsPanel.setLayout(PaymentsPanelLayout);
        PaymentsPanelLayout.setHorizontalGroup(
            PaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentsPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(orgAccountPaymentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TradeGoodsSoldButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SubdryAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ORGdonationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(PaymentToAccountantButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminManageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PaymentsPanelLayout.setVerticalGroup(
            PaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentsPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(orgAccountPaymentButton)
                .addGap(33, 33, 33)
                .addComponent(TradeGoodsSoldButton)
                .addGap(31, 31, 31)
                .addComponent(SubdryAccountButton)
                .addGap(36, 36, 36)
                .addComponent(ORGdonationButton)
                .addGap(42, 42, 42)
                .addComponent(PaymentToAccountantButton)
                .addGap(36, 36, 36)
                .addComponent(adminManageButton)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        PaymentCalculatorPanel.setBackground(new java.awt.Color(255, 255, 255));

        PaymentCalculatorHeaderLabel.setForeground(new java.awt.Color(0, 0, 0));
        PaymentCalculatorHeaderLabel.setText("--------------- Payment Calculator -------------");

        TotalInLabel.setForeground(new java.awt.Color(0, 0, 0));
        TotalInLabel.setText("Total:");

        NumberOfUsersLabel.setForeground(new java.awt.Color(0, 0, 0));
        NumberOfUsersLabel.setText("Number Of Users: ");

        MarauderSquadronLabel.setForeground(new java.awt.Color(0, 0, 0));
        MarauderSquadronLabel.setText("Marauder Squadron Cut:");

        DividerLabel.setForeground(new java.awt.Color(0, 0, 0));
        DividerLabel.setText("------------------------------------------------------");

        TotalProfitsLabel.setForeground(new java.awt.Color(0, 0, 0));
        TotalProfitsLabel.setText("Total Profits");

        PaymentPerUserLabel.setForeground(new java.awt.Color(0, 0, 0));
        PaymentPerUserLabel.setText("Payment Per User:");

        PaymentToMarauderSquadron.setForeground(new java.awt.Color(0, 0, 0));
        PaymentToMarauderSquadron.setText("Payment to Marauder");

        CalculateButton.setText("Calculate");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        TotalInTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalInTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaymentCalculatorPanelLayout = new javax.swing.GroupLayout(PaymentCalculatorPanel);
        PaymentCalculatorPanel.setLayout(PaymentCalculatorPanelLayout);
        PaymentCalculatorPanelLayout.setHorizontalGroup(
            PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentCalculatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentCalculatorPanelLayout.createSequentialGroup()
                        .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PaymentCalculatorHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PaymentCalculatorPanelLayout.createSequentialGroup()
                                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(MarauderSquadronLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NumberOfUsersLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TotalInLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TotalInTextField)
                                    .addComponent(NumberOfUsersIntextField)
                                    .addComponent(MarauderSquadInTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(DividerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addGroup(PaymentCalculatorPanelLayout.createSequentialGroup()
                        .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TotalProfitsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PaymentPerUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PaymentToMarauderSquadron, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TotalProfitsOutTextField)
                            .addComponent(PaymentPerUserOutTextField)
                            .addComponent(PaymentToMarauderOut)))
                    .addComponent(CalculateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        PaymentCalculatorPanelLayout.setVerticalGroup(
            PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentCalculatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaymentCalculatorHeaderLabel)
                .addGap(18, 18, 18)
                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalInLabel)
                    .addComponent(TotalInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumberOfUsersLabel)
                    .addComponent(NumberOfUsersIntextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MarauderSquadronLabel)
                    .addComponent(MarauderSquadInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(DividerLabel)
                .addGap(18, 18, 18)
                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalProfitsLabel)
                    .addComponent(TotalProfitsOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentPerUserLabel)
                    .addComponent(PaymentPerUserOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentToMarauderSquadron)
                    .addComponent(PaymentToMarauderOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabel)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OperationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PaymentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(PaymentCalculatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PaymentCalculatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PaymentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OperationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TotalInTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalInTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalInTextFieldActionPerformed

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        calculator(Integer.parseInt(TotalInTextField.getText()), Integer.parseInt(NumberOfUsersIntextField.getText()), Integer.parseInt(MarauderSquadInTextField.getText()));
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void JButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton6ActionPerformed
        int ID = 6;
        new Operation().setVisible(true);
        dispose();
    }//GEN-LAST:event_JButton6ActionPerformed

    private void JButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton1ActionPerformed
        int ID = 1;
        new Operation().setVisible(true);
        dispose();
    }//GEN-LAST:event_JButton1ActionPerformed

    private void orgAccountPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgAccountPaymentButtonActionPerformed
        new PaymentToOrg().setVisible(true);
        dispose();
    }//GEN-LAST:event_orgAccountPaymentButtonActionPerformed

    private void adminManageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminManageButtonActionPerformed
        new AdminPortal().setVisible(true);
        dispose();
    }//GEN-LAST:event_adminManageButtonActionPerformed

    private void JButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton3ActionPerformed
        int ID = 3;
        new Operation().setVisible(true);
        dispose();
    }//GEN-LAST:event_JButton3ActionPerformed

    private void JButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton2ActionPerformed
        int ID = 2;
        new Operation().setVisible(true);
        dispose();
    }//GEN-LAST:event_JButton2ActionPerformed

    private void JButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton4ActionPerformed
        int ID = 4;
        new Operation().setVisible(true);
        dispose();
    }//GEN-LAST:event_JButton4ActionPerformed

    private void JButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton5ActionPerformed
         int ID = 5;
        new Operation().setVisible(true);
        dispose();
    }//GEN-LAST:event_JButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
            }
        });
    }

    public void calculator(int total, int numberOfUser, int marauderSquadronCut) {
        int totalProfits = 0;
        int PaymentPerUser = 0;
        int PaymentToMaruader = 0;

        totalProfits = (int) (total - (total * 0.005));

        PaymentToMaruader = (int) (totalProfits * marauderSquadronCut);
        PaymentPerUser = (totalProfits - PaymentToMaruader) / numberOfUser;

        TotalProfitsOutTextField.setText(totalProfits + "");
        PaymentToMarauderOut.setText(PaymentToMaruader + "");
        PaymentPerUserOutTextField.setText(PaymentPerUser + "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private javax.swing.JLabel DividerLabel;
    private javax.swing.JButton JButton1;
    private javax.swing.JButton JButton2;
    private javax.swing.JButton JButton3;
    private javax.swing.JButton JButton4;
    private javax.swing.JButton JButton5;
    private javax.swing.JButton JButton6;
    private javax.swing.JTextField MarauderSquadInTextField;
    private javax.swing.JLabel MarauderSquadronLabel;
    private javax.swing.JTextField NumberOfUsersIntextField;
    private javax.swing.JLabel NumberOfUsersLabel;
    private javax.swing.JButton ORGdonationButton;
    private javax.swing.JPanel OperationsPanel;
    private javax.swing.JLabel PaymentCalculatorHeaderLabel;
    private javax.swing.JPanel PaymentCalculatorPanel;
    private javax.swing.JLabel PaymentPerUserLabel;
    private javax.swing.JTextField PaymentPerUserOutTextField;
    private javax.swing.JButton PaymentToAccountantButton;
    private javax.swing.JTextField PaymentToMarauderOut;
    private javax.swing.JLabel PaymentToMarauderSquadron;
    private javax.swing.JPanel PaymentsPanel;
    private javax.swing.JButton SubdryAccountButton;
    private javax.swing.JLabel TotalInLabel;
    private javax.swing.JTextField TotalInTextField;
    private javax.swing.JLabel TotalProfitsLabel;
    private javax.swing.JTextField TotalProfitsOutTextField;
    private javax.swing.JButton TradeGoodsSoldButton;
    private javax.swing.JButton adminManageButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton orgAccountPaymentButton;
    // End of variables declaration//GEN-END:variables
}
