/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author dazzl
 */
public class UserDashboard extends javax.swing.JFrame {

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        OperationsPanel = new javax.swing.JPanel();
        operationButton3 = new javax.swing.JButton();
        operationButton4 = new javax.swing.JButton();
        operationButton5 = new javax.swing.JButton();
        operationButton6 = new javax.swing.JButton();
        operationButton7 = new javax.swing.JButton();
        operationButton2 = new javax.swing.JButton();
        operationButton1 = new javax.swing.JButton();
        PaymentsPanel = new javax.swing.JPanel();
        orgAccountPaymentButton = new javax.swing.JButton();
        TradeGoodsSoldButton = new javax.swing.JButton();
        SubdryAccountButton = new javax.swing.JButton();
        ORGdonationButton = new javax.swing.JButton();
        PaymentToAccountantButton = new javax.swing.JButton();
        PaymentCalculatorPanel = new javax.swing.JPanel();
        PaymentCalculatorHeaderLabel = new javax.swing.JLabel();
        TotalInLabel = new javax.swing.JLabel();
        NumberOfUsersLabel = new javax.swing.JLabel();
        MarauderSquadronLabel = new javax.swing.JLabel();
        DividerLabel = new javax.swing.JLabel();
        TotalProfitsLabel = new javax.swing.JLabel();
        TotalProfitsOutTextField = new javax.swing.JTextField();
        PaymentPerUserLabel = new javax.swing.JLabel();
        PaymentPerUserOutTextField = new javax.swing.JTextField();
        PaymentToMarauderSquadron = new javax.swing.JLabel();
        PaymentToMarauderOut = new javax.swing.JTextField();
        CalculateButton = new javax.swing.JButton();
        TotalInTextField = new javax.swing.JTextField();
        NumberOfUsersIntextField = new javax.swing.JTextField();
        MarauderSquadInTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerLabel.setText("---------------------------------------------------- WELCOME ----------------------------------------------------------------");

        OperationsPanel.setBackground(new java.awt.Color(255, 255, 255));

        operationButton3.setText("jButton1");

        operationButton4.setText("jButton2");

        operationButton5.setText("jButton3");

        operationButton6.setText("jButton4");

        operationButton7.setText("jButton5");

        operationButton2.setText("jButton6");

        operationButton1.setText("Jbutton6");

        javax.swing.GroupLayout OperationsPanelLayout = new javax.swing.GroupLayout(OperationsPanel);
        OperationsPanel.setLayout(OperationsPanelLayout);
        OperationsPanelLayout.setHorizontalGroup(
            OperationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperationsPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(OperationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(operationButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(operationButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operationButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operationButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operationButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operationButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operationButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        OperationsPanelLayout.setVerticalGroup(
            OperationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperationsPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(operationButton1)
                .addGap(18, 18, 18)
                .addComponent(operationButton2)
                .addGap(30, 30, 30)
                .addComponent(operationButton3)
                .addGap(35, 35, 35)
                .addComponent(operationButton4)
                .addGap(36, 36, 36)
                .addComponent(operationButton5)
                .addGap(43, 43, 43)
                .addComponent(operationButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(operationButton7)
                .addGap(47, 47, 47))
        );

        PaymentsPanel.setBackground(new java.awt.Color(255, 255, 255));

        orgAccountPaymentButton.setText("Payment to Org Account");

        TradeGoodsSoldButton.setText("Log Trade goods sold");

        SubdryAccountButton.setText("Sundry Payments");

        ORGdonationButton.setText("ORG ACCOUNT DONATION");

        PaymentToAccountantButton.setText("Payment to Accountant");

        javax.swing.GroupLayout PaymentsPanelLayout = new javax.swing.GroupLayout(PaymentsPanel);
        PaymentsPanel.setLayout(PaymentsPanelLayout);
        PaymentsPanelLayout.setHorizontalGroup(
            PaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentsPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(orgAccountPaymentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TradeGoodsSoldButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SubdryAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ORGdonationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(PaymentToAccountantButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PaymentsPanelLayout.setVerticalGroup(
            PaymentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentsPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(orgAccountPaymentButton)
                .addGap(33, 33, 33)
                .addComponent(TradeGoodsSoldButton)
                .addGap(31, 31, 31)
                .addComponent(SubdryAccountButton)
                .addGap(36, 36, 36)
                .addComponent(ORGdonationButton)
                .addGap(42, 42, 42)
                .addComponent(PaymentToAccountantButton)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        PaymentCalculatorPanel.setBackground(new java.awt.Color(255, 255, 255));

        PaymentCalculatorHeaderLabel.setForeground(new java.awt.Color(0, 0, 0));
        PaymentCalculatorHeaderLabel.setText("--------------- Payment Calculator -------------");

        TotalInLabel.setForeground(new java.awt.Color(0, 0, 0));
        TotalInLabel.setText("Total:");

        NumberOfUsersLabel.setForeground(new java.awt.Color(0, 0, 0));
        NumberOfUsersLabel.setText("Number Of Users: ");

        MarauderSquadronLabel.setForeground(new java.awt.Color(0, 0, 0));
        MarauderSquadronLabel.setText("Marauder Squadron Cut:");

        DividerLabel.setForeground(new java.awt.Color(0, 0, 0));
        DividerLabel.setText("------------------------------------------------------");

        TotalProfitsLabel.setForeground(new java.awt.Color(0, 0, 0));
        TotalProfitsLabel.setText("Total Profits");

        PaymentPerUserLabel.setForeground(new java.awt.Color(0, 0, 0));
        PaymentPerUserLabel.setText("Payment Per User:");

        PaymentToMarauderSquadron.setForeground(new java.awt.Color(0, 0, 0));
        PaymentToMarauderSquadron.setText("Payment to Marauder");

        CalculateButton.setText("Calculate");

        TotalInTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalInTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaymentCalculatorPanelLayout = new javax.swing.GroupLayout(PaymentCalculatorPanel);
        PaymentCalculatorPanel.setLayout(PaymentCalculatorPanelLayout);
        PaymentCalculatorPanelLayout.setHorizontalGroup(
            PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentCalculatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentCalculatorPanelLayout.createSequentialGroup()
                        .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PaymentCalculatorHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PaymentCalculatorPanelLayout.createSequentialGroup()
                                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(MarauderSquadronLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NumberOfUsersLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TotalInLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TotalInTextField)
                                    .addComponent(NumberOfUsersIntextField)
                                    .addComponent(MarauderSquadInTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(DividerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addGroup(PaymentCalculatorPanelLayout.createSequentialGroup()
                        .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TotalProfitsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PaymentPerUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PaymentToMarauderSquadron, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TotalProfitsOutTextField)
                            .addComponent(PaymentPerUserOutTextField)
                            .addComponent(PaymentToMarauderOut)))
                    .addComponent(CalculateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        PaymentCalculatorPanelLayout.setVerticalGroup(
            PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentCalculatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaymentCalculatorHeaderLabel)
                .addGap(18, 18, 18)
                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalInLabel)
                    .addComponent(TotalInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumberOfUsersLabel)
                    .addComponent(NumberOfUsersIntextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MarauderSquadronLabel)
                    .addComponent(MarauderSquadInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(DividerLabel)
                .addGap(18, 18, 18)
                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalProfitsLabel)
                    .addComponent(TotalProfitsOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentPerUserLabel)
                    .addComponent(PaymentPerUserOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PaymentCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentToMarauderSquadron)
                    .addComponent(PaymentToMarauderOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabel)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OperationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PaymentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(PaymentCalculatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PaymentCalculatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PaymentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OperationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TotalInTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalInTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalInTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private javax.swing.JLabel DividerLabel;
    private javax.swing.JTextField MarauderSquadInTextField;
    private javax.swing.JLabel MarauderSquadronLabel;
    private javax.swing.JTextField NumberOfUsersIntextField;
    private javax.swing.JLabel NumberOfUsersLabel;
    private javax.swing.JButton ORGdonationButton;
    private javax.swing.JPanel OperationsPanel;
    private javax.swing.JLabel PaymentCalculatorHeaderLabel;
    private javax.swing.JPanel PaymentCalculatorPanel;
    private javax.swing.JLabel PaymentPerUserLabel;
    private javax.swing.JTextField PaymentPerUserOutTextField;
    private javax.swing.JButton PaymentToAccountantButton;
    private javax.swing.JTextField PaymentToMarauderOut;
    private javax.swing.JLabel PaymentToMarauderSquadron;
    private javax.swing.JPanel PaymentsPanel;
    private javax.swing.JButton SubdryAccountButton;
    private javax.swing.JLabel TotalInLabel;
    private javax.swing.JTextField TotalInTextField;
    private javax.swing.JLabel TotalProfitsLabel;
    private javax.swing.JTextField TotalProfitsOutTextField;
    private javax.swing.JButton TradeGoodsSoldButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton operationButton1;
    private javax.swing.JButton operationButton2;
    private javax.swing.JButton operationButton3;
    private javax.swing.JButton operationButton4;
    private javax.swing.JButton operationButton5;
    private javax.swing.JButton operationButton6;
    private javax.swing.JButton operationButton7;
    private javax.swing.JButton orgAccountPaymentButton;
    // End of variables declaration//GEN-END:variables
}
